title: Carlos Raffellini
description: Carlos Raffellini
url: charlyraffellini.github.io # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog

# Comments
discus_identifier: charlyraffellini

# Social settings
twitter_url: https://twitter.com/raffellinic
facebook_url: https://www.facebook.com/carlos.raffellini
googleplus_url: https://plus.google.com/+carlosraffellini
instagram_url: https://instagram.com
github_url: https://github.com/charlyraffellini/


# Set the Sass partials directory, as we're using @imports
sass:
  sass_dir: _sass
  style: :expanded # You might prefer to minify using :compressed

# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem



# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-65317889-1

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
highlighter: rouge